#ifndef ERROR_H
#define ERROR_H

typedef enum {
    UNRECOGNIZED_TOKEN,
    UNCLOSED_COMMENT,
    TOKEN_TOO_LONG,
    UNCLOSED_STRING,
    EXTRA_DECIMAL_POINT,
    MISSING_TOKEN_FOUND_TOKEN,
    MISSING_TOKEN_FOUND_OTHER,
    MISSING_OTHER_FOUND_TOKEN,
    MISSING_OTHER_FOUND_OTHER,
    DUPLICATE_DECLARATION,
    ILLEGAL_ARRAY_LEN,
    UNDECLARED_SYMBOL,
    NONVAR_ASSMT_DEST,
    NOT_AN_ARRAY,
    NOT_A_PROC
} error_type;

void print_error(char* file_name, error_type type, int line, ...);

#endif